Add ofPort ipAddress learning
smartxworks/lynx pull request #19
Opened 2021-03-12 10:36 UTC by echkenluo

2021-03-12 12:27 UTC, kylezh requested changes
需要补充一个单测

2021-03-12 12:27 UTC, kylezh commented on pkg/monitor/agent.go
> +	var ipAddrs []types.IPAddress
这个要放到第一个 for 里面，不然会导致 ip 被累积添加到 ipAddrs 里面

2021-03-13 04:14 UTC, echkenluo commented on pkg/monitor/agent.go
> +	var ipAddrs []types.IPAddress
是放里面合理，我改下。因为 map 值每次都只有一个 endpoint 信息送来，不会影响结果，就放外面了。

2021-03-15 01:26 UTC, kylezh requested changes

2021-03-15 01:26 UTC, kylezh commented on pkg/monitor/agent.go
> +}
这种函数就不用封装了

2021-03-15 05:07 UTC, kylezh commented on pkg/monitor/agent.go
> +	monitor.HandleOfPortIpAddressUpdate(monitor.ofPortIpAddressMonitorChan, stopChan)
missing `go`

2021-03-16 03:03 UTC, kylezh commented on pkg/monitor/agent_test.go
> +	}
需要补充 oldOfPort 移除的情况

2021-03-16 03:39 UTC, kylezh approved these changes

2021-03-16 03:39 UTC, merged