Add policyrule controller
smartxworks/lynx pull request #25
Opened 2021-03-17 01:48 UTC by echkenluo

2021-03-17 06:30 UTC, kylezh requested changes

2021-03-17 06:30 UTC, kylezh commented on pkg/agent/controller/policyrule/policyrule_controller.go
> +	// +kubebuilder:scaffold:imports
这个有必要么？

2021-03-17 06:30 UTC, kylezh commented on pkg/agent/controller/policyrule/policyrule_controller.go
> +	flag.Parse()
flag 相关的都放到 cmd/ 下面

2021-03-17 06:30 UTC, kylezh commented on pkg/agent/controller/policyrule/policyrule_controller.go
> +	// your logic here
删掉这个注释

2021-03-17 06:30 UTC, kylezh commented on pkg/agent/controller/policyrule/policyrule_controller.go
> +	// PolicyRule status update ?
这里至少 log 一下

2021-03-17 06:30 UTC, kylezh commented on pkg/agent/controller/policyrule/policyrule_controller.go
> +		// Update policyRule enforce status for statistics and display. TODO
？

2021-03-17 06:30 UTC, kylezh commented on pkg/agent/controller/policyrule/policyrule_controller.go
> +	}
这里和 addPolicyRule 有重复逻辑，可以合并成一个函数

2021-03-17 06:30 UTC, kylezh commented on pkg/agent/controller/policyrule/policyrule_controller.go
> +		// Update policyRule enforce status for statistics and display. TODO
？

2021-03-17 06:43 UTC, echkenluo commented on pkg/agent/controller/policyrule/policyrule_controller.go
> +		// Update policyRule enforce status for statistics and display. TODO
policyrule 对应 flow 下发/删除 实施状态，如果对应的 flow 下发/删除不成功可以更新 policyrule 的 status，可以用于 lynx controller 获取与展示 policyrule 的作用状态或统计  securityPolicy 相关的 policyrule 信息。

2021-03-17 06:43 UTC, echkenluo commented on pkg/agent/controller/policyrule/policyrule_controller.go
> +		// Update policyRule enforce status for statistics and display. TODO
同 delpolicyrule

2021-03-17 06:45 UTC, echkenluo commented on pkg/agent/controller/policyrule/policyrule_controller.go
> +	// +kubebuilder:scaffold:imports
这行应该可以去掉

2021-03-17 08:02 UTC, kylezh requested changes

2021-03-17 08:02 UTC, kylezh commented on pkg/agent/controller/policyrule/policyrule_controller_test.go
> +	})
1. 两个 testcase 之间不能有依赖
2. 每个 testcase 都应该自己做 setup 和 teardown

2021-03-18 01:41 UTC, kylezh commented on pkg/agent/controller/policyrule/policyrule_controller.go
> +	// Add logic
这里需要判断是否是一个 delete 事件，如果是 delete 事件，需要触发 delete 逻辑

2021-03-18 05:49 UTC, closed without merging